# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7072532f98eb5ae5bb228f1d1d1a7d22ab39125e30319605c5414860775b1650146d9761e653d0766256fe3310178d023b793ef3c1359b6f65c0563572fa5c36

test:
  secret_key_base: 683333a5d5f4c19411a170a9ff2df19c16edb1814d906835f56b2069de88d019bad142b883694621df9adee1e2a0fdb7db6ab6e3ca1de7977c0912f83968e3db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
